name: release-please  # 工作流名称：自动化版本与发布管理

on:
  push:
    branches:
      - main  # 当代码合并或推送到 main 分支时触发

# 赋予自动更新仓库内容、创建 Release PR 以及发布版本所需的权限
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          # 自定义 Release Please 配置文件
          config-file: .github/release-please-config.json

          # 版本清单文件
          manifest-file: .github/.release-please-manifest.json