# 自动管理 Python 项目 的版本号更新、变更日志（Changelog）生成以及 GitHub Release 的创建
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: penshot
